# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
- 'on': ['@all']
  'require':
    'frameworks/extra-cmake-modules': '@latest-kf5'
    'frameworks/kdoctools': '@latest-kf5'
    'frameworks/kio': '@latest-kf5'
    'frameworks/ki18n': '@latest-kf5'
    'frameworks/kconfig': '@latest-kf5'
    'frameworks/kconfigwidgets': '@latest-kf5'
    'frameworks/kdbusaddons': '@latest-kf5'
    'frameworks/kidletime': '@latest-kf5'
    'frameworks/kjobwidgets': '@latest-kf5'
    'frameworks/knotifications': '@latest-kf5'
    'frameworks/kwindowsystem': '@latest-kf5'
    'frameworks/kxmlgui': '@latest-kf5'
    'frameworks/ktextwidgets': '@latest-kf5'
    'frameworks/kcalendarcore': '@latest-kf5'
    'frameworks/kstatusnotifieritem': '@latest-kf5'
    'frameworks/kcmutils': '@latest-kf5'

Options:
  require-passing-tests-on: [ 'Linux', 'FreeBSD' ]
